name: update readme

on: 
  schedule:
    - cron: 0 */6 * * *

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
          uses: actions/checkout@v4
      - name: setup node
          uses: actions/setup-node@v4
          with:
            node-version: 18.x
            cache: npm
      - name: run script
        run: node update.js
